### ISSUE TITLE
website request

### ISSUE THREAD

**Issue by sephithdarknesse** [LogicalSoIutions/TwitchEmbedBlocker#2]
https://albiononline2d.com/

Another website thats doing this, for Blackboa's stream. Wasnt sure where else to request this, so here seemed good enough. Thanks for making the extension!

**Comment by LogicalSoIutions** [comment]
Added. Updating both Firefox and Chrome extensions now!

**Comment by LogicalSoIutions** [comment]
BTW - Firefox is updated. Chrome still pending.

**Comment by sephithdarknesse** [comment]
You're so fast! Props to keeping things up to date so quickly
