### ISSUE TITLE
Domain requests for common New World websites

### ISSUE THREAD

**Issue by DeaftJoe** [LogicalSoIutions/TwitchEmbedBlocker#3]
#2 I'd like to request the following sites:

aeternum-map.gg
nwdb.info

And as a follow-up: are you able to parameterize the list of domains the extension runs on, allowing for users to add/remove domains independently?

Thanks for your time.

**Comment by LogicalSoIutions** [comment]
I can work on the follow up later - will work on getting these two New World websites added for now however.

**Comment by LogicalSoIutions** [comment]
Does not look like aeternum-map.gg has any Twitch embeds?

**Comment by LogicalSoIutions** [comment]
v1.0.7 approved on Firefox/Chrome ~ added nwdb.info
